import React, { useCallback, useEffect, useState } from "react";
import { CheckCircle2, RefreshCw } from "lucide-react";
import { toast } from "sonner";

import { Button } from "../../components/ui/button";
import { Dialog, DialogContent, DialogFooter, DialogHeader, DialogTitle } from "../../components/ui/dialog";
import { EmptyState } from "../../components/ui/empty-state";
import { SurfacePanel, SurfacePanelHeader } from "../../components/ui/surface-panel";
import { Table, TableBody, TableCell, TableHead, TableHeader, TableRow } from "../../components/ui/table";
import { TechnicalLabel } from "../../components/ui/technical-label";
import { Textarea } from "../../components/ui/textarea";
import { useAuth } from "../../context/AuthContext";
import { useI18n } from "../../i18n";
import { alertActions, inventoryApi, parseInventoryConflict, statusTone, validInventoryReason } from "../../lib/inventory";
import { AdminLayout } from "./AdminLayout";


export default function RestockAlerts() {
  const { t } = useI18n(); const { user } = useAuth(); const actions = alertActions(user?.permissions || []); const [status, setStatus] = useState("active"); const [rows, setRows] = useState([]); const [loading, setLoading] = useState(true); const [error, setError] = useState(""); const [resolving, setResolving] = useState(null);
  const load = useCallback(async () => { setLoading(true); setError(""); try { setRows(await inventoryApi.alerts({ status, limit: 500 })); } catch (requestError) { setError(parseInventoryConflict(requestError.response?.data?.detail)); } finally { setLoading(false); } }, [status]);
  useEffect(() => { load(); }, [load]);
  return <AdminLayout title={t("admin.restockAlerts")} subtitle={t("inventory.alertSubtitle")}><SurfacePanel><SurfacePanelHeader padding="sm" className="flex flex-wrap items-center justify-between gap-3"><TechnicalLabel>{t("inventory.alerts")}</TechnicalLabel><Button variant="outline" size="sm" onClick={load}><RefreshCw className="mr-2 h-4 w-4" />{t("common.refresh")}</Button></SurfacePanelHeader><div className="p-4"><label className="space-y-1"><TechnicalLabel>{t("common.status")}</TechnicalLabel><select value={status} onChange={(event) => setStatus(event.target.value)} className="h-10 w-full max-w-xs border border-border bg-background px-3"><option value="active">Active</option><option value="resolved">Resolved</option></select></label></div></SurfacePanel><SurfacePanel className="mt-4">{loading ? <EmptyState>{t("common.loading")}</EmptyState> : error ? <EmptyState><span role="alert">{error}</span></EmptyState> : rows.length === 0 ? <EmptyState>{t("inventory.noAlerts")}</EmptyState> : <Table><TableHeader><TableRow><TableHead>{t("inventory.subject")}</TableHead><TableHead>{t("inventory.trigger")}</TableHead><TableHead>{t("common.status")}</TableHead><TableHead>{t("inventory.metrics")}</TableHead><TableHead>{t("inventory.recipients")}</TableHead><TableHead>{t("common.updated")}</TableHead>{actions.includes("resolve") && <TableHead className="text-right">{t("common.actions")}</TableHead>}</TableRow></TableHeader><TableBody>{rows.map((alert) => <TableRow key={alert.id}><TableCell><div className="font-semibold">{alert.subject_name || alert.subject_id}</div><TechnicalLabel size="micro">{alert.subject_type}</TechnicalLabel></TableCell><TableCell><TechnicalLabel tone={alert.trigger_type === "projected_shortage" ? "danger" : "warning"}>{alert.trigger_type}</TechnicalLabel></TableCell><TableCell><TechnicalLabel tone={statusTone(alert.status)}>{alert.status}</TechnicalLabel></TableCell><TableCell><div className="text-xs">Available: {alert.last_balance?.available ?? "—"}</div><div className="text-xs">Projected: {alert.last_balance?.projected ?? "—"}</div></TableCell><TableCell>{alert.recipient_count ?? t("inventory.roleRecipients")}</TableCell><TableCell>{alert.updated_at ? new Date(alert.updated_at).toLocaleString() : "—"}</TableCell>{actions.includes("resolve") && <TableCell className="text-right">{alert.status === "active" && <Button variant="outline" size="sm" onClick={() => setResolving(alert)}><CheckCircle2 className="mr-2 h-4 w-4" />{t("inventory.resolve")}</Button>}</TableCell>}</TableRow>)}</TableBody></Table>}</SurfacePanel>{resolving && <ResolveDialog alert={resolving} onClose={() => setResolving(null)} onResolved={() => { setResolving(null); load(); }} />}</AdminLayout>;
}
function ResolveDialog({ alert, onClose, onResolved }) { const { t } = useI18n(); const [reason, setReason] = useState(""); const [busy, setBusy] = useState(false); const resolve = async () => { setBusy(true); try { await inventoryApi.resolveAlert(alert.id, reason.trim()); toast.success(t("inventory.resolveSuccess")); onResolved(); } catch (error) { toast.error(parseInventoryConflict(error.response?.data?.detail)); } finally { setBusy(false); } }; return <Dialog open onOpenChange={(open) => !open && onClose()}><DialogContent><DialogHeader><DialogTitle>{t("inventory.resolve")} · {alert.subject_name || alert.subject_id}</DialogTitle></DialogHeader><Textarea value={reason} onChange={(event) => setReason(event.target.value)} maxLength={500} placeholder={t("common.reason")} /><DialogFooter><Button variant="outline" onClick={onClose}>{t("common.cancel")}</Button><Button disabled={busy || !validInventoryReason(reason)} onClick={resolve}>{t("inventory.resolve")}</Button></DialogFooter></DialogContent></Dialog>; }
