import React, { useCallback, useEffect, useMemo, useState } from "react";
import { RefreshCw } from "lucide-react";

import { Button } from "../../components/ui/button";
import { EmptyState } from "../../components/ui/empty-state";
import { Input } from "../../components/ui/input";
import { SurfacePanel, SurfacePanelHeader } from "../../components/ui/surface-panel";
import { Table, TableBody, TableCell, TableHead, TableHeader, TableRow } from "../../components/ui/table";
import { TechnicalLabel } from "../../components/ui/technical-label";
import { useI18n } from "../../i18n";
import { inventoryApi, parseInventoryConflict } from "../../lib/inventory";
import { AdminLayout } from "./AdminLayout";


export default function StockMovements() {
  const { t } = useI18n(); const [rows, setRows] = useState([]); const [loading, setLoading] = useState(true); const [error, setError] = useState(""); const [filters, setFilters] = useState({ subject_type: "", subject_id: "", reference_id: "", movement_type: "", actor: "", date: "" });
  const load = useCallback(async () => { setLoading(true); setError(""); try { setRows(await inventoryApi.movements({ subject_type: filters.subject_type, subject_id: filters.subject_id, reference_id: filters.reference_id, limit: 500 })); } catch (requestError) { setError(parseInventoryConflict(requestError.response?.data?.detail)); } finally { setLoading(false); } }, [filters.subject_type, filters.subject_id, filters.reference_id]);
  useEffect(() => { load(); }, [load]);
  const visible = useMemo(() => rows.filter((row) => (!filters.movement_type || row.movement_type === filters.movement_type) && (!filters.actor || String(row.created_by || "").includes(filters.actor)) && (!filters.date || String(row.created_at || "").startsWith(filters.date))), [rows, filters.movement_type, filters.actor, filters.date]);
  const set = (field) => (event) => setFilters({ ...filters, [field]: event.target.value });
  return <AdminLayout title={t("admin.stockMovements")} subtitle={t("inventory.historySubtitle")}><SurfacePanel><SurfacePanelHeader padding="sm" className="flex justify-between"><TechnicalLabel>{t("inventory.immutableHistory")}</TechnicalLabel><Button variant="outline" size="sm" onClick={load}><RefreshCw className="mr-2 h-4 w-4" />{t("common.refresh")}</Button></SurfacePanelHeader><div className="grid gap-3 p-4 md:grid-cols-3 xl:grid-cols-6"><Filter label={t("inventory.subjectType")}><select value={filters.subject_type} onChange={set("subject_type")} className="h-10 w-full border border-border bg-background px-3"><option value="">{t("common.all")}</option><option value="material">Material</option><option value="product_variant">Product variant</option></select></Filter><Filter label={t("inventory.subjectId")}><Input value={filters.subject_id} onChange={set("subject_id")} /></Filter><Filter label={t("inventory.movementType")}><Input value={filters.movement_type} onChange={set("movement_type")} /></Filter><Filter label={t("inventory.referenceId")}><Input value={filters.reference_id} onChange={set("reference_id")} /></Filter><Filter label={t("inventory.actor")}><Input value={filters.actor} onChange={set("actor")} /></Filter><Filter label={t("common.date")}><Input type="date" value={filters.date} onChange={set("date")} /></Filter></div></SurfacePanel><SurfacePanel className="mt-4">{loading ? <EmptyState>{t("common.loading")}</EmptyState> : error ? <EmptyState><span role="alert">{error}</span></EmptyState> : visible.length === 0 ? <EmptyState>{t("inventory.noMovements")}</EmptyState> : <Table><TableHeader><TableRow><TableHead>{t("common.date")}</TableHead><TableHead>{t("inventory.subject")}</TableHead><TableHead>{t("inventory.movementType")}</TableHead><TableHead>{t("inventory.quantity")}</TableHead><TableHead>{t("inventory.beforeAfter")}</TableHead><TableHead>{t("inventory.reference")}</TableHead><TableHead>{t("common.reason")}</TableHead><TableHead>{t("inventory.actor")}</TableHead></TableRow></TableHeader><TableBody>{visible.map((row) => <TableRow key={row.id}><TableCell className="whitespace-nowrap">{new Date(row.created_at).toLocaleString()}</TableCell><TableCell><TechnicalLabel>{row.subject_type}</TechnicalLabel><div>{row.subject_id}</div></TableCell><TableCell>{row.movement_type}</TableCell><TableCell>{row.quantity}</TableCell><TableCell>v{row.balance_version_before} → v{row.balance_version_after}</TableCell><TableCell>{row.reference_type}<br />{row.reference_id}</TableCell><TableCell>{row.reason || "—"}</TableCell><TableCell>{row.created_by || "—"}</TableCell></TableRow>)}</TableBody></Table>}</SurfacePanel></AdminLayout>;
}
function Filter({ label, children }) { return <label className="space-y-1"><TechnicalLabel>{label}</TechnicalLabel>{children}</label>; }
